name: h1_mimic_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - cmake
  - build-essential
  - nodejs  # Optional, useful for some tensorboard plugins
  - pip:
      - uv  # Much faster pip alternative
      # Base simulation
      - --extra-index-url https://pypi.nvidia.com
      - isaacsim[all,extscache]==5.1.0
      # Deep Learning
      - --index-url https://download.pytorch.org/whl/cu128
      - torch==2.7.0
      - torchvision==0.22.0
      - tensorboard
      # Retargeting & ASAP requirements
      - mujoco
      - chumpy
      - scipy
      - numpy
      - joblib
      - omegaconf
      - matplotlib
